version: '3.3'

services:
  stable-diffusion:
    container_name: sd
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env_docker
    volumes:
      - .:/sd
      - ./models:/sd/models
      - ./src:/sd/src
      - ./outputs:/sd/outputs
      - conda_env:/opt/conda
      - root_profile:/root
    ports:
      - '7860:7860'
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

volumes:
  conda_env:
  root_profile:
